max_moves_for_own_color: 1
min_perc_for_own_color_move: .05
max_moves_for_opposing_color: 8
min_move_perc_for_opposing_color: .05
max_move: 6
move_selection_rating_weight: .2
move_selection_win_perc_weight: .7
move_selection_stockfish_weight: .05
move_selection_popularity_weight: .05
min_games: 1000

move_selection_rating_preprocessing: quantile
move_selection_win_perc_preprocessing: none
move_selection_stockfish_preprocessing: min_max_inversed_for_black
move_selection_popularity_preprocessing: none

starting_board_config: rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1

driver_path: r"C:\Users\Tristan\Documents\chess\chromedriver.exe"
engine_path: r"C:\Users\Tristan\Documents\chess\stockfish-windows-2022-x86-64-avx2.exe"
output_directory: r"C:\Users\Tristan\Documents\chess\output"
